version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - db:/var/lib/mysql
  auth:
    depends_on:
      - mysqldb
    build: 
      context: ./micro-auhentication
      target: development
    env_file: ./.env
    ports:
      - 9000:9000
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  gateway:
    depends_on:
      - auth
      - restaurant
    build: 
      context: ./micro-gateway
      target: development
    env_file: ./.env
    ports:
      - 8080:8080
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  restaurant:
    depends_on:
      - auth
    build: 
      context: ./micro-restaurant
      target: development
    env_file: ./.env
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
