name: github-actions
run-name: docker-ci
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Initialize containers
        run: |
            set -x

            docker version

            docker run --rm hello-world