name: Build and Test
run-name: docker-ci
on: [push]
jobs:
  build_projects:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: setup java
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'
        - name: Tests verification
          run: |  
            mvn surefire:test failsafe:integration-test -f ./micro-authentication/pom.xml
            mvn surefire:test failsafe:integration-test -f ./micro-gateway/pom.xml
            mvn surefire:test failsafe:integration-test -f ./micro-restaurant/pom.xml